import { Router, type IRouter } from "express";
import healthRouter from "./health";
import charactersRouter from "./characters";
import comicsRouter from "./comics";
import worldsRouter from "./worlds";
import timelineRouter from "./timeline";
import encyclopediaRouter from "./encyclopedia";
import newsRouter from "./news";
import galleryRouter from "./gallery";
import originalsRouter from "./originals";
import storiesRouter from "./stories";
import subscriptionRouter from "./subscription";
import libraryRouter from "./library";
import searchRouter from "./search";
import universeRouter from "./universe";
import novelsRouter from "./novels";
import storeRouter from "./store";
import writersRouter from "./writers";
import cardsRouter from "./cards";

import adminUsersRouter from "./admin/users";
import adminCharactersRouter from "./admin/characters";
import adminComicsRouter from "./admin/comics";
import adminWorldsRouter from "./admin/worlds";
import adminEncyclopediaRouter from "./admin/encyclopedia";
import adminNewsRouter from "./admin/news";
import adminDashboardRouter from "./admin/dashboard";
import adminTimelineRouter from "./admin/timeline";
import adminMediaRouter from "./admin/media";
import adminAuditRouter from "./admin/audit";
import adminOriginalsRouter from "./admin/originals";
import adminStoriesRouter from "./admin/stories";
import adminEpisodesRouter from "./admin/episodes";
import adminSubscriptionsRouter from "./admin/subscriptions";
import adminPaymentsRouter from "./admin/payments";
import adminGenresRouter from "./admin/genres";

import meRouter from "./me";
import commentsRouter from "./comments";
import reviewsRouter from "./reviews";
import collectionsRouter from "./collections";
import writerStudioRouter from "./writer-studio";
import notificationsRouter from "./notifications";
import adminSchedulesRouter from "./admin/schedules";

const router: IRouter = Router();

router.use(healthRouter);
router.use(meRouter);
router.use(charactersRouter);
router.use(comicsRouter);
router.use(worldsRouter);
router.use(timelineRouter);
router.use(encyclopediaRouter);
router.use(newsRouter);
router.use(galleryRouter);
router.use(originalsRouter);
router.use(storiesRouter);
router.use(subscriptionRouter);
router.use(libraryRouter);
router.use(searchRouter);
router.use(universeRouter);
router.use(novelsRouter);
router.use(storeRouter);
router.use(writersRouter);
router.use(cardsRouter);
router.use(commentsRouter);
router.use(reviewsRouter);
router.use(collectionsRouter);
router.use(writerStudioRouter);
router.use(notificationsRouter);
router.use("/admin/dashboard", adminDashboardRouter);
router.use("/admin/users", adminUsersRouter);
router.use("/admin/characters", adminCharactersRouter);
router.use("/admin/comics", adminComicsRouter);
router.use("/admin/worlds", adminWorldsRouter);
router.use("/admin/encyclopedia", adminEncyclopediaRouter);
router.use("/admin/news", adminNewsRouter);
router.use("/admin/timeline", adminTimelineRouter);
router.use("/admin/media", adminMediaRouter);
router.use("/admin/audit", adminAuditRouter);
router.use("/admin/originals", adminOriginalsRouter);
router.use("/admin/stories", adminStoriesRouter);
router.use("/admin/episodes", adminEpisodesRouter);
router.use("/admin/subscriptions", adminSubscriptionsRouter);
router.use("/admin/payments", adminPaymentsRouter);
router.use("/admin/genres", adminGenresRouter);
router.use("/admin/schedules", adminSchedulesRouter);

export default router;
